name: Manual Deployment Workflow for live

on:
  workflow_dispatch:

jobs:
  test:
    name: "Run unit tests"
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        name: "Checkout reporsitory"

      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

  linter:
    name: "Run linter"
    defaults:
      run:
        shell: bash
        working-directory: ./src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkput reporsitory"

      - name: "Install dependencies"
        run: npm install

      - name: "Run linter"
        run: npx standard -v

  deploy-prod:
    name: "Deploy PR for LIVE ENV"
    needs: [test, linter]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: "Trigger Deploy Hook for LIVE ENV"
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
