name: Continous Integration workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout repository"

      - name: "Install Dependencies"
        run: npm install

      - name: "Run test"
        run: npm run test

  lint:
    name: "Run linter"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout repository"
      - name: "Install dependencies"
        run: npm run install
      - name: "Run standard linter"
        run: npx standard -v
