name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        name: "Checkout reporsitory"

      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

  linter:
    name: "Run linter"
    defaults:
      run:
        shell: bash
        working-directory: ./src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkput reporsitory"

      - name: "Install dependencies"
        run: npm install

      - name: "Run linter"
        run: npx standard -v
